# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'f0ef7336-47e7-4bc0-93f3-0494139f5600'

  # Agent VM image name
  # vmImageName: 'ubuntu-latest'

stages:
- template: templates/stg.yml  # Template reference
  parameters:
    name: 'build'
    vmImage: 'ubuntu-latest'
