parameters:
  name: ''
  env: ''
  agentname: 'ubuntu-latest'
  azureSubscription: 'f0ef7336-47e7-4bc0-93f3-0494139f5600'

stages:

- stage: ${{ parameters.name }}
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: ${{ parameters.env }}
    variables:
    - group: Release
    pool:
      vmImage: ${{ parameters.agentname }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: helloworld-nodejs-27869'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(WebAppNameDev)
              runtimeStack: 'NODE|16-lts'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'
